export const projects = [
  {
    id: 0,
    name: "Color scheme generator",
    githubUrl: "https://github.com/vickydarlinn/color-scheme-generator",
    liveUrl: "https://color-scheme-generator-vickydarlinn.netlify.app/",
    isBigProject: false,
  },
  {
    id: 1,
    name: "Movie Watchlist",
    githubUrl: "https://github.com/vickydarlinn/Movie-watchlist",
    liveUrl: "https://movie-watchlist-vickydarlinn.netlify.app/",
    isBigProject: false,
  },
  {
    id: 2,
    name: "Todo in reactJs",
    githubUrl: "https://github.com/vickydarlinn/todo-react-app",
    liveUrl: "https://todo-react-app-topaz.vercel.app/",
    isBigProject: false,
  },
  {
    id: 3,
    name: "Namaste React Bootcamp learning",
    githubUrl: "https://github.com/vickydarlinn/vickyNamasteReact",
    liveUrl: "https://github.com/vickydarlinn",
    isBigProject: false,
  },
  {
    id: 4,
    name: "Redux Learning project",
    githubUrl: "https://github.com/vickydarlinn/redux_learning",
    liveUrl: "https://redux-learning-one.vercel.app/",
    isBigProject: false,
  },
  {
    id: 5,
    name: "Anshu Small Shop",
    githubUrl: "https://github.com/vickydarlinn/anshuSmallShop",
    liveUrl: "https://anshu-small-shop.vercel.app/",
    isBigProject: true,
  },
  {
    id: 6,
    name: "mini js projects",
    githubUrl: "https://github.com/vickydarlinn/small_js_projects",
    liveUrl: "https://github.com/vickydarlinn/small_js_projects",
    isBigProject: false,
  },
];
